Repository qgises/qgis-es, pull requests merged in 2020-09, with the labels that each got.

#17 Create Post “test-post/index”
  content/post/test-post/index.md
Labels: netlify-cms/pending_review

#30 Update Author “miguel-sevilla/_index”
  content/authors/miguel-sevilla/_index.md
Labels: netlify-cms/draft

#31 Update Author “gus-presa/_index”
  content/authors/gus-presa/_index.md
  content/authors/gus-presa/foto_gus_qgis.jpg
Labels: netlify-cms/draft

#32 Update Author “gus-presa/_index”
  content/authors/gus-presa/_index.md
Labels: netlify-cms/pending_publish

#33 Update Author “carmen-diez/_index”
  content/authors/carmen-diez/_index.md
  content/authors/carmen-diez/carmen_diez.jpg
Labels: netlify-cms/pending_publish

#34 Update Author “luigi-pirelli/_index”
  content/authors/luigi-pirelli/_index.md
Labels: netlify-cms/pending_publish

#42 Update Author “josep-lluis-sala/_index”
  content/authors/josep-lluis-sala/_index.md
  content/authors/josep-lluis-sala/avatar.jpg
Labels: netlify-cms/draft

#43 Update Author “josep-lluis-sala/_index”
  content/authors/josep-lluis-sala/_index.md
Labels: netlify-cms/pending_publish

#44 Update Author “lucho-ferrer/_index”
  content/authors/lucho-ferrer/_index.md
  content/authors/lucho-ferrer/avatar.jpg
Labels: netlify-cms/pending_publish

#45 Update Author “lucho-ferrer/_index”
  content/authors/lucho-ferrer/avatar.jpg
Labels: netlify-cms/pending_publish

#46 Update Author “miguel-sevilla/_index”
  content/authors/miguel-sevilla/_index.md
  content/authors/miguel-sevilla/avatar.jpg
Labels: netlify-cms/pending_publish

#47 Update Author “carlospsig/_index”
  content/authors/carlospsig/_index.md
Labels: netlify-cms/pending_publish

#48 Update Author “carlospsig/_index”
  content/authors/carlospsig/_index.md
Labels: netlify-cms/pending_publish

#49 Update Author “admin/_index”
  content/authors/admin/_index.md
Labels: netlify-cms/pending_publish

#50 Update Author “lucho-ferrer/_index”
  content/authors/lucho-ferrer/_index.md
Labels: netlify-cms/pending_publish

#51 Update Author “lucho-ferrer/_index”
  content/authors/lucho-ferrer/_index.md
Labels: netlify-cms/pending_publish

#52 Update Author “lucho-ferrer/_index”
  content/authors/lucho-ferrer/_index.md
Labels: netlify-cms/pending_publish

#53 Update Author “lucho-ferrer/_index”
  content/authors/lucho-ferrer/_index.md
Labels: netlify-cms/pending_publish

#54 Update Author “lucho-ferrer/_index”
  content/authors/lucho-ferrer/_index.md
Labels: netlify-cms/pending_publish
